language: node_js

node_js:
  - "11.4"

# This env  property uses the build matrix to run tests in each sub-xcode_project
# https://lord.io/blog/2014/travis-multiple-subdirs/
# TODO(bigpopakap): figure out how to make this work when the other subdirectories are added
env:
  - TEST_DIR=client

script: cd $TEST_DIR && npm install && npm test
